### GENERAL SETTINGS ###

# Site settings
title: el13ucidator
description: Echoes In the Cyberdust
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: https://el13ucidator.github.io

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#0047AB"
  primary_rgb: "0, 71, 171" 
  secondary: "#E34234"
  link: "#428bca"
  link_hover: "01b2fe"
  footer_heading: "#bfc9d3"
  footer_content: "#E34234"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, dribble, facebook, twitter, instagram, tumblr, etc). Shown in footer.
#social:
 # - title: dribble
  #  url:
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
 # - lines: 
  #  - Some Ave, 987,
   # - 23890, New York,
    #- United States.
#email: hello@solidtheme.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
#members:
 # - name: Mark Webber
  #  position: CEO
  #  text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
   # img: team01.jpg
    #social:
     # - title: envelope #use for email address
      #  url: mailto:name@domain.com
      #- title: twitter
       # url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
#clients:
 # - name: dribbble
  #  img: client01.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "short about"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "testmonial"
    author: 
    position: 